spring:
  config:
    activate:
      on-profile: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petclinic
    username: root
    password: petclinic
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  profiles:
    active: mysql
